import type { Metadata } from "next";
import LocalFont from "next/font/local";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = LocalFont({
  src: [
    {
      path: './fonts/Gelion Regular.woff',
      weight: "400",
      style: "normal"
    },
    {
      path: './fonts/Gelion Bold.woff',
      weight: "700",
      style: "normal"
    },
    {
      path: './fonts/Gelion Medium.woff',
      weight: "500",
      style: "normal"
    }
  ],
  display: "swap"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">      
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
